### ISSUE TITLE
Get notifications about backend failures

### ISSUE THREAD

**Issue by eranelbaz** [opentofu/registry-alpha#106]
Related to #4 

Specs -
- Get notification for each 5xx and 4xx 
   - The notification should contain info
- Add the option to mute some notifications (let's say we don't want to get for 404)
- Shouldn't block the regular flow

Tech design

- Log errors to cloud watch
- Use [Lambda and cloud watch integration](https://docs.aws.amazon.com/lambda/latest/dg/services-cloudwatchlogs.html) to trigger lambda for each log
   - https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html#LambdaFunctionExample we can `put-subscription-filter` to filter logs and not get trigger for each log line we are writing
- Webhook call to the notification destination on relevant logs 
   - log lever `error`
   - status code `5xx` or `4xx`

**Comment by Yantrio** [comment]
I feel like this should be done as a layer on top of this repository.

I don't like the idea of doing `OpenTofu` specific things that stop other people also using this repo.

**Comment by eranelbaz** [comment]
IMO this one can also be optional webhook calls, so it doesn't really stop anyone
