### ISSUE TITLE
Return deprecation warning for `hashicorp/terraform` provider usage

### ISSUE THREAD

**Issue by yaronya** [opentofu/registry-alpha#108]
Legacy registry returns this warning when requesting the `hashicorp/terraform` provider:
```
╷
│ Warning: Additional provider information from registry
│ 
│ The remote registry returned warnings for registry.terraform.io/hashicorp/terraform:
│ - This provider is archived and no longer needed. The terraform_remote_state data source is built into the latest Terraform release.
╵
```

This could be added easily in OpenTofu registry by attaching a `Warnings` attribute to response body.
See more details in https://github.com/opentofu/opentofu/issues/613

**Comment by kislerdm** [comment]
@yaronya hey Yaron! I can take care of the issue today/tomorrow. Please let me know if that's acceptable time frame as I feel that it may be a minor blocker for alpha release. Thanks!

**Comment by yaronya** [comment]
Sure, feel free to grab it :)
It is not a blocker to the alpha release, but we do want to get this done soon 🙏
