### ISSUE TITLE
Add explicit linting configuration as `.golangci.yml`

### ISSUE THREAD

**Issue by kislerdm** [opentofu/registry-alpha#112]
## Acceptance Criteria

- The file . golangci.yml is colocated with the codebase
- It contains the list of linters and their configurations for us to rely on

**Comment by Yantrio** [comment]
The linting is configured here already: https://github.com/opentofu/registry/blob/main/src/.golangci.yml

**Comment by kislerdm** [comment]
Sorry, my bad - didn't notice it 😄
