### ISSUE TITLE
Modules that use `X.X.X` tags don't work with the opentofu registry

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/registry-alpha#121]
**Problem Summary**
Using this registry, when attempting to use a module such as [stack-config](https://github.com/cloudposse/terraform-yaml-stack-config), for which the tags are in format `X.X.X` instead of `vX.X.X`, the registry gives the wrong redirect URL

Try doing `tofu init` with the following configuration:
```
module "stack-config" {
  source  = "registry.opentofu.org/cloudposse/stack-config/yaml"
  version = "1.5.0"
}
```
and you will get the following error:
```
│ Error: Failed to download module
│
│   on main.tf line 24:
│   24: module "stack-config" {
│
│ Could not download module "stack-config" (main.tf:24) source code from "git::https://github.com/cloudposse/terraform-yaml-stack-config?ref=v1.5.0": error downloading 'https://github.com/cloudposse/terraform-yaml-stack-config?ref=v1.5.0': /usr/bin/git exited with 1:
│ error: pathspec 'v1.5.0' did not match any file(s) known to git
```

**Reason**:
The registry assumes that all modules are using `vX.X.X` tags (in this case `v1.5.0`), when some modules are actually using `X.X.X` (in this case `1.5.0`)
We should make sure to return the correct tag in `moduleDownload`, we'd probably need to fetch releases again in order to figure out what's the actual tag (though that should be fine with the DDB cache)

**Comment by RLRabinowitz** [comment]
Note - we should also consider if this affects providers. There might be existing providers out there that have the `X.X.X` format for tags, but I didn't find any yet

**Comment by Yantrio** [comment]
I've done some background reading, and I can safely say that the `v` prefix on tags/releases is only optional for modules.

For providers this is mandatory.

Therefore I think we can do some conditional checking for module versions and not worry about providers
