### ISSUE TITLE
Switch to use `tofu` in this repository

### ISSUE THREAD

**Issue by eranelbaz** [opentofu/registry-alpha#134]
Swap all uses to OpenTofu when we have a release
Notable areas are
- CD process
- Readme

**Comment by cube2222** [comment]
Very strongly against.

This creates a chicken-and-egg problem where if we break the registry, we can't deploy it anymore.

**Comment by eranelbaz** [comment]
This will force us to use our product, which help us have more confidence in it.
if there is any issue we can always rollback to deploy locally (using the remote S3 BE)

**Comment by cube2222** [comment]
> we can always rollback to deploy locally (using the remote S3 BE)

We should never need to do that, esp. during an incident when we're trying to get it back working - as much as possible should be automated in that case. You will also not have the secrets locally.

What we **could** do, is have a private registry that mirrors the providers and modules our deployment needs. Then we could use tofu with that without the chicken-and-egg problem. But that's a lot of work and I believe out of scope for now.

I propose we close this issue for now.

**Comment by eranelbaz** [comment]
I belive we can postpone that for after stable release
