### ISSUE TITLE
Create CI for our IaC

### ISSUE THREAD

**Issue by eranelbaz** [opentofu/registry-alpha#138]
Add GitHub action that runs on Pull Requests that only runs `plan` command and reports if it finished successfully or found issues

**Comment by eranelbaz** [comment]
I'll work on that after my last issue

**Comment by eranelbaz** [comment]
We decided to postpone this issue as it compromises our AWS account - anyone can run plans and read all the data they want

**Comment by Yantrio** [comment]
I discussed this with @eranelbaz and @cube2222 and I am very much against this approach.

In my opinion I would like to keep all executions of IaC as locked down as possible and keep things using the [Principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege). 

I understand that we may feel it's helpful, but on a public repository I feel like this does not suit a public repository.

I propose that we keep a strict review processes ongoing here and re-review this later on down the line.

**Comment by eranelbaz** [comment]
I still do not understand the security issue as we can run this CI only for approved PRs like we have in OpenTofu/OpenTofu repository, this still keep the strict review process as we'll only approve and run those PRs which we read and trust
