### ISSUE TITLE
Response code for module download is 200, it has to be 204

### ISSUE THREAD

**Issue by rumenvasilev** [opentofu/registry-alpha#157]
While I was building the [API specification](https://github.com/rumenvasilev/terraform-registry-api/tree/main/model) for the registry I stumbled on this. In short, when a module download request is served, the response body is empty. The download URL is delivered by means of `X-Terraform-Get` header. The implementation of the registry here wrongly returns HTTP 200, which mandates non-empty body content. Since there's none, the response code should in fact be 204.

This won't be a breaking change, rather it would bring it more in-line with the standard and what is also implemented in Hashicorp's terraform registry.

A bit more data:
- Hashicorp's registry returns 204 (try it out with `curl -v https://registry.terraform.io/v1/modules/terraform-aws-modules/iam/aws/5.30.0/download`)
- Terraform supports both 200 and 204 as valid response codes - https://github.com/hashicorp/terraform/blob/main/internal/registry/client.go#L237
- Opentofu also supports both 200 and 204 as valid response codes - https://github.com/opentofu/opentofu/blob/main/internal/registry/client.go#L237

**Comment by Yantrio** [comment]
I agree on this one, and I just triple checked the spec https://www.rfc-editor.org/rfc/rfc9110.html#name-204-no-content

It does mention (in a roundabout way) that metadata in the headers is fine for a 204 :)
