### ISSUE TITLE
Prepare the project for collaboration

### ISSUE THREAD

**Issue by Yantrio** [opentofu/registry-alpha#16]
This step is needed so that we can work on developing this with more engineers.

In the shared AWS account we should introduce

- S3 bucket for state storage (and hook up the TF in this repo to use it)
- Secrets manager setup to share github token that we generate

In our domain setup for opentf.org, we should be ready to set up the subdomain and introduce the namesevers given as output 

## Heads up for work required from other people:

- @omry-hay Once we have the nameservers, we will be in touch to set up a domain. Most likely `registry.opentf.org` for now.
- @cube2222 Or whoever owns the github org, we should probably use a github service account PAT. I'm not sure if we have this anywhere else so let's discuss this here if we dont.

**Comment by omry-hay** [comment]
> This step is needed so that we can work on developing this with more engineers.
> 
> In the shared AWS account we should introduce
> 
> * S3 bucket for state storage (and hook up the TF in this repo to use it)
> * Secrets manager setup to share github token that we generate
> 
> In our domain setup for opentf.org, we should be ready to set up the subdomain and introduce the namesevers given as output
> 
> ## Heads up for work required from other people:
> * @omry-hay Once we have the nameservers, we will be in touch to set up a domain. Most likely `registry.opentf.org` for now.
> * @cube2222 Or whoever owns the github org, we should probably use a github service account PAT. I'm not sure if we have this anywhere else so let's discuss this here if we don't.

@Yantrio Nameserver are up and configured - https://dnschecker.org/#NS/registry.opentf.org

**Comment by Yantrio** [comment]
Tracking PAT in a separate issue now.
