### ISSUE TITLE
Registry not in sync for google provider

### ISSUE THREAD

**Issue by terlar** [opentofu/registry-alpha#160]
As I understand it the registry is based on GitHub releases, but everytime I tried to use the OpenTofu registry it fails getting the google provider, later than `5.2.0`.

However there is `5.3.0` and `5.4.0`:
https://github.com/hashicorp/terraform-provider-google/releases

For now I have had to use explicit provider source `registry.terraform.io/hashicorp/google` in order to bypass the lagging versions.

Am I doing something wrong or is there some issue with the registry?

**Comment by Yantrio** [comment]
This is most likely an issue with the registry. I will investigate this now for you

**Comment by Yantrio** [comment]
This should now be working please try again and let me know. Thanks for reporting this. If you hit any other issues with the registry please feel free to reach out 👍 Thanks!

**Comment by terlar** [comment]
Yes, this is working now! Thank you for the quick fix. I will keep extra attention regarding the registry and report back if I run into any other issues. 🎉
