### ISSUE TITLE
Create CD for deploying registry code to production

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/registry-alpha#49]
Currently the registry's IaC and code are being deployed locally. It's hard to follow who deployed what to production
We should have a GHA that runs those deployments, and only use that:

GHA should basically `opentf/terraform init` and `opentf/terraform apply`, with the correct configuration, with a configurable branch

**Comment by RLRabinowitz** [comment]
@cube2222 / @Yantrio , for this GHA, we'd need to set AWS credentials for the GHA. Either using assume role, or having static credentials for an IAM user

Can you please try and setup credentials that could be used as part of this GHA?

**Comment by Yantrio** [comment]
Credentials were set up and communicated to you privately. Please feel free to move forward with this.

**Comment by eranelbaz** [comment]
@Yantrio Hey, can you please set up the credentials as github secrets?
So I could login into the S3 backend and run terraform?

**Comment by eranelbaz** [comment]
@Yantrio IMO we can close this one per #135 + #110
correct?

**Comment by Yantrio** [comment]
Yes
