### ISSUE TITLE
Investigate if we need to implement the pagination API

### ISSUE THREAD

**Issue by Yantrio** [opentofu/registry-alpha#8]
There is a pagination api in the registry that is documented, however I have never seen this in use.

We should look into if we need to implement this, especially for some of the providers that have a LOT of versioning ongoing.

**Comment by RLRabinowitz** [comment]
Pagaination isn't necessary for OpenTF, as it is not used at all by the CLI
There's an old implementation `NewPaginationMeta`, but it is not used. Current logic does not expect pagination ever

If we'll ever decide that we require pagination for any of the APIs for any other reason, then we will implement it. But for now, YAGNI
