### ISSUE TITLE
Migration of lambdas to `provided.al2` runtime

### ISSUE THREAD

**Issue by kislerdm** [opentofu/registry-alpha#87]
## Problem

The aws lambdas are configured to use the `go1.x` runtime, which will be deprecated on 2023-12-31.

## Proposed solution

Migrate to the `provided.al2` runtime. See details [here](https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/).

**Comment by Yantrio** [comment]
Hi @kislerdm!

Thanks for raising this, on the back of this I have raised PR #89 to resolve this issue. Thanks!
